#' Lipid Network Plot
#'
#' Generates a network plot using known lipid metabolism pathways
#' to visualize class-based enrichment statistics. Uses a manually
#' curated collection of pathways as a reference. Lipid class
#' annotations assigned by this reference enable mapping of any
#' untargeted or targeted lipidomics dataset onto the network.
#'
#' @param d_enrch Enrichment results list generated by ms_stat_crich()
#' or a univariate results object containing lipid class ratios
#' (only applicable if net_type is "class_comp").
#' Only required when network type is "annotation", "enrichment", or
#' "class_comp".
#' @param net_type Output network type. Currently supported types are
#' "pathways_legend", "base", "annotation", "enrichment", or "class_comp".
#' @param cl_var Clustering variable to use for aggregating lipid classes.
#' @param comp1 Comparison name for plotting enrichment statistics. Currently
#' supports up to one comparison name.
#' @param comp_sat Should unsaturated and saturated lipid classes be compared?
#' Enter a logical value (TRUE/FALSE) to toggle lipid saturation comparisons.
#' This parameter is dependent upon the presence of both unsaturated and
#' saturated lipid classes in the enrichment statistics data frame.
#' @return A network plot of the specified type.
#' @examples
#'
#' # ## Pathway Legend
#' # ms_plot_lipidnet(
#' #   net_type = "pathways_legend"
#' # )
#' # ## Base network
#' # ms_plot_lipidnet(
#' #   net_type = "base"
#' # )
#' # ## Plot dataset annotations
#' # ms_plot_lipidnet(
#' #   d_enrch = d[["chemrich"]],
#' #   net_type = "annotation",
#' #   cl_var = "label_saturation"
#' # )
#' # ## Plot dataset enrichment results
#' # ms_plot_lipidnet(
#' #   d_enrch = d[["chemrich"]],
#' #   net_type = "enrichment",
#' #   cl_var = "label_saturation",
#' #   comp1 = "HFA_F-BR",
#' #   comp_sat = TRUE
#' # )
#' # ## Plot lipid class ratio changes
#' # ms_plot_lipidnet(
#' # )
#'
#' @export
ms_plot_lipidnet <- function( # nolint
  d_enrch = NULL,
  net_type,
  cl_var = NULL,
  comp1 = NULL,
  comp_sat = NULL
) {
  # Load enrichment results from each platform, nodes, and edges
  ## Untargeted
  d1 <- read.table(
    "analyze/table_enrichment_saturation_LSAE.txt",
    sep = "\t",
    header = TRUE,
    comment.char = "",
    quote = ""
  )
  ## Oxys
  d2 <- read.table(
    "analyze/table_enrichment_class_oxy.txt",
    sep = "\t",
    header = TRUE,
    comment.char = "",
    quote = ""
  )
  ## Nodes
  nnode <- read.table(
    "nodes_v01.txt",
    sep = "\t",
    header = TRUE,
    comment.char = "",
    quote = ""
  )
  ## Edges
  nedge <- read.table(
    "edges_v01.txt",
    sep = "\t",
    header = TRUE,
    comment.char = "",
    quote = ""
  )
  # Resolve classes that aren't present in node names
  d2[["label"]] <- d2[["Major_pathway"]]
  d2 <- setNames(d2, names(d1))
  d <- rbind(d1, d2)
  unique(d[["label"]])
  d <- d[!grepl("MGDG|aLPE", d[["label"]]), ]
  unique(d[["label"]]) %in% nn[[1]]
  #---- Base network ----
  if(net_type == "base") { # nolint
    # Create network
    np <- igraph::graph_from_data_frame(
      ne,
      vertices = nn
    )
    npl <- ggraph::create_layout(np, layout = "stress", circular = FALSE)
    # define boundary polygon for each subclass
    npw <- dplyr::bind_rows(
      lapply(
        unique(npl[["synthesis.pathway"]]),
        function(i) {
          d1 <- npl[npl[["synthesis.pathway"]] == i, ]
          y1 <- d1[d1[["x"]] < quantile(d1[["x"]], 0.5), ]
          y1 <- y1[order(y1[["y"]]), ]
          y2 <- d1[d1[["x"]] > quantile(d1[["x"]], 0.5), ]
          y2 <- y2[order(y2[["y"]], decreasing = TRUE), ]
          d4 <- dplyr::bind_rows(y1, y2)[, c("x", "y")]
          d4[["pw"]] <- i
          d2 <- data.frame(
            "x" = c(
              min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
              min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
              max(d1[["x"]]) + abs(0.15 * max(d1[["x"]])),
              max(d1[["x"]]) + abs(0.15 * max(d1[["x"]]))
            ),
            "y" = c(
              min(d1[["y"]]) - abs(0.15 * min(d1[["y"]])),
              max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
              max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
              min(d1[["y"]]) - abs(0.15 * min(d1[["y"]]))
            ),
            "pw" = i
          )
          # if (nrow(d1) >= 4) {
          #   d2 <- data.frame(
          #     "x" = c(
          #       min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
          #       min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
          #       max(d1[["x"]]) + abs(0.15 * max(d1[["x"]])),
          #       max(d1[["x"]]) + abs(0.15 * max(d1[["x"]]))
          #     ),
          #     "y" = c(
          #       min(d1[["y"]]) - abs(0.15 * min(d1[["y"]])),
          #       max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
          #       max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
          #       min(d1[["y"]]) - abs(0.15 * min(d1[["y"]]))
          #     )
          #   )
          #   ?smoothr::smooth()
          #   sf::st_as_sf(d4, coords = c(1:2))
          #   test <- sf::st_as_sf(d4, coords = c(1:2))
          #   test <- sf::st_combine(test)
          #   test <- sf::st_cast(test, "POLYGON")
          #   test <- smoothr::smooth(test, method = "chaikin", refinements = 10)
          #   test <- as.data.frame(sf::st_coordinates(test))
          #   test[["pw"]] <- i
          #   d4 <- setNames(test[, c(1, 2, 5)], c("x", "y", "pw"))
          # }
          return(d2) # nolint
        }
      )
    )
    npw[["pw"]] <- factor(
      npw[["pw"]],
      levels = c(
        "Phospholipid Biosynthesis", "Fatty Acid Biosynthesis",
        "Lipid Transport", "Plasmalogen Biosynthesis",
        "Oxylipin Biosynthesis", "Sterol Lipid Biosynthesis",
        "Cholesterol Catabolism", "Sphingolipid Biosynthesis",
        "Glycerolipid Biosynthesis"
      )
    )
    ## Plot
    np_base <- ggraph::ggraph(npl) + # Base graph
      # Subclass shading
      ggplot2::geom_polygon(
        data = npw,
        ggplot2::aes(
          x = .data[["x"]], # nolint
          y = .data[["y"]],
          fill = .data[["pw"]]
        ),
        color = "grey25",
        alpha = 1
      ) +
      # node points
      ggraph::geom_node_point() +
      # graph edges and attributes
      ggraph::geom_edge_link(
        ggplot2::aes(label = .data[["enzyme.id"]]), # nolint
        label_dodge = ggplot2::unit(2, "mm"),
        angle_calc = "along",
        alpha = 0.5,
        label_alpha = 0.0,
        color = "grey50"
      ) +
      # color scheme
      ggplot2::scale_fill_manual(
        "Pathway",
        values = col_univ() # nolint
      ) +
      # text labels
      ggrepel::geom_text_repel(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]],
          label = .data[["name"]]
        ),
        bg.color = "grey10",
        color = "white",
        bg.r = 0.03,
        alpha = 1,
        nudge_x = 0.25,
        nudge_y = 0.1,
        size = 5
      ) +
      # plot theme
      gen_theme() + # nolint
      net_theme(leg = c(0.8, 0.1)) # nolint
  }
  #---- Annotation network ----
  if(net_type == "annotation") { # nolint
    head(d)
    unique(d[["Comparison"]])
    net1 <- d[d[["Comparison"]] == "SHN-LHN", ]
    # Map dataset annotations
    net_anno <- setNames(aggregate(
      unique(net1[, c("label", "n")])[["n"]], # nolint
      list(unique(net1[, c("label", "n")])[["label"]]),
      function(x) sum(x)
    ), c("Node", "cluster_size"))
    ## Adjust node attributes
    nn <- dplyr::left_join(
      nn,
      net_anno,
      by = "Node"
    )
    nn[["cluster_size"]] <- ifelse(
      is.na(nn[["cluster_size"]]),
      0,
      nn[["cluster_size"]]
    )
    nn[["set_alpha"]] <- (
      (nn[["cluster_size"]] - min(nn[["cluster_size"]])) /
        (max(nn[["cluster_size"]])) - min(nn[["cluster_size"]])
    )
    nn[["set_clus_size"]] <- (
      (nn[["cluster_size"]] - min(nn[["cluster_size"]])) /
        (max(nn[["cluster_size"]])) - min(nn[["cluster_size"]])
    )
    ## Adjust edge attributes
    ne[["set_alpha_edge"]] <- ifelse(
      ne[["from"]] %in%
        nn[nn[["set_clus_size"]] > 0, "Node"],
      1,
      0.25
    )
    # Network
    np <- igraph::graph_from_data_frame(
      ne,
      vertices = nn
    )
    npl <- ggraph::create_layout(np, layout = "stress", circular = FALSE)
    # define boundary polygon for each subclass
    npw <- dplyr::bind_rows(
      lapply(
        unique(npl[["synthesis.pathway"]]),
        function(i) {
          d1 <- npl[npl[["synthesis.pathway"]] == i, ]
          y1 <- d1[d1[["x"]] < quantile(d1[["x"]], 0.5), ]
          y1 <- y1[order(y1[["y"]]), ]
          y2 <- d1[d1[["x"]] > quantile(d1[["x"]], 0.5), ]
          y2 <- y2[order(y2[["y"]], decreasing = TRUE), ]
          d4 <- dplyr::bind_rows(y1, y2)[, c("x", "y")]
          d4[["pw"]] <- i
          d2 <- data.frame(
            "x" = c(
              min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
              min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
              max(d1[["x"]]) + abs(0.15 * max(d1[["x"]])),
              max(d1[["x"]]) + abs(0.15 * max(d1[["x"]]))
            ),
            "y" = c(
              min(d1[["y"]]) - abs(0.15 * min(d1[["y"]])),
              max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
              max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
              min(d1[["y"]]) - abs(0.15 * min(d1[["y"]]))
            ),
            "pw" = i
          )
          return(d2) # nolint
        }
      )
    )
    npw[["pw"]] <- factor(
      npw[["pw"]],
      levels = c(
        "Phospholipid Biosynthesis", "Fatty Acid Biosynthesis",
        "Lipid Transport", "Plasmalogen Biosynthesis",
        "Oxylipin Biosynthesis", "Sterol Lipid Biosynthesis",
        "Cholesterol Catabolism", "Sphingolipid Biosynthesis",
        "Glycerolipid Biosynthesis"
      )
    )
    # Plot Annotations
    ## Plot
    np_anno <- ggraph::ggraph(npl) + # Base graph
      # Subclass shading
      ggplot2::geom_polygon(
        data = npw,
        ggplot2::aes(
          x = .data[["x"]], # nolint
          y = .data[["y"]],
          fill = .data[["pw"]]
        ),
        color = "grey25",
        alpha = 1
      ) +
      # edge attributes
      ggraph::geom_edge_link(
        ggplot2::aes(
          label = ifelse(
            .data[["set_alpha_edge"]] == 0.25, # nolint
            "",
            .data[["enzyme.id"]]
          ),
          alpha = .data[["set_alpha_edge"]]
        ),
        label_dodge = ggplot2::unit(2, "mm"),
        alpha = 0.5,
        label_alpha = 0.0,
        angle_calc = "along",
        color = "grey50",
        show.legend = FALSE
      ) +
      # node points
      ggraph::geom_node_point(
        ggplot2::aes(
          alpha = ifelse(
            .data[["set_alpha"]] == 0, # nolint
            1,
            0
          )
        ),
        color = "grey50",
        show.legend = FALSE
      ) +
      ggraph::geom_node_point(
        ggplot2::aes(
          size = .data[["cluster_size"]] * 1
        ),
        show.legend = FALSE
      ) +
      # color scheme
      ggplot2::scale_fill_manual(
        "Pathway",
        values = col_univ() # nolint
      ) +
      ggplot2::scale_size_area(
        max_size = 16
      ) +
      # text labels
      ggrepel::geom_text_repel(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]],
          label = .data[["name"]]
        ),
        bg.color = "grey10",
        color = "white",
        bg.r = 0.03,
        alpha = 1,
        nudge_x = 0.25,
        nudge_y = 0.1,
        size = 5
      ) +
      # plot theme
      gen_theme() + # nolint
      net_theme(leg = c(0.8, 0.1)) # nolint

      ggplot2::ggsave(
        "net_anno.png",
        np_anno,
        width = 15,
        height = 10,
        dpi = 500
      )
  }

  #---- Enrichment network ----
  if(net_type == "enrichment") { # nolint
    net1 <- d[d[["Comparison"]] == "SNN-LNN" & d[["Region"]] == "cells", ]
    nn <- nnode
    ne <- nedge
    # Map dataset annotations
    net_anno <- setNames(aggregate(
      unique(net1[, c("label", "n")])[["n"]], # nolint
      list(unique(net1[, c("label", "n")])[["label"]]),
      function(x) sum(x)
    ), c("Node", "cluster_size"))
    ## Adjust node attributes
    nn <- dplyr::left_join(
      nn,
      net_anno,
      by = "Node"
    )
    nn[["cluster_size"]] <- ifelse(
      is.na(nn[["cluster_size"]]),
      0,
      nn[["cluster_size"]]
    )
    nn[["set_alpha"]] <- (
      (nn[["cluster_size"]] - min(nn[["cluster_size"]])) /
        (max(nn[["cluster_size"]])) - min(nn[["cluster_size"]])
    )
    nn[["set_clus_size"]] <- (
      (nn[["cluster_size"]] - min(nn[["cluster_size"]])) /
        (max(nn[["cluster_size"]])) - min(nn[["cluster_size"]])
    )
    ## Adjust edge attributes
    ne[["set_alpha_edge"]] <- ifelse(
      ne[["from"]] %in%
        nn[nn[["set_clus_size"]] > 0, "Node"],
      1,
      0.25
    )
    # Map enrichment statistics
    ## Join enrichment results with network plot
    if(length(comp1) == 1 && comp_sat == TRUE) { # nolint
      net1[["Saturation"]] <- ifelse(
        grepl("\\.Uns|\\.uns", net1[["label.saturation"]]),
        "Unsat",
        ifelse(
          grepl("\\.Sat|\\.sat", net1[["label.saturation"]]),
          "Sat",
          ""
        )
      )
      cmp <- unique(net1[["Comparison"]])
      net_enrch <- as.data.frame(tidyr::pivot_wider(
        net1[, c( # nolint
          "Comparison", "label", "Saturation",
          "Ratio", "FDR", "n"
        )],
        names_from = c(.data[["Comparison"]], .data[["Saturation"]]), # nolint
        values_from = c(.data[["Ratio"]], .data[["FDR"]], .data[["n"]])
      ))
      net_name1 <- names(net_enrch[, 2:ncol(net_enrch)]) # nolint
      net_enrch[["Node"]] <- net_enrch[["label"]]
      nn <- dplyr::left_join(
        nn,
        net_enrch,
        by = "Node"
      )
      ## Network
      np <- igraph::graph_from_data_frame(
        ne,
        vertices = nn
      )
      ## Network layout
      npl <- ggraph::create_layout(np, layout = "stress", circular = FALSE)
      # define boundary polygon for each subclass
      npw <- dplyr::bind_rows(
        lapply(
          unique(npl[["synthesis.pathway"]]),
          function(i) {
            d1 <- npl[npl[["synthesis.pathway"]] == i, ]
            y1 <- d1[d1[["x"]] < quantile(d1[["x"]], 0.5), ]
            y1 <- y1[order(y1[["y"]]), ]
            y2 <- d1[d1[["x"]] > quantile(d1[["x"]], 0.5), ]
            y2 <- y2[order(y2[["y"]], decreasing = TRUE), ]
            d4 <- dplyr::bind_rows(y1, y2)[, c("x", "y")]
            d4[["pw"]] <- i
            d2 <- data.frame(
              "x" = c(
                min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
                min(d1[["x"]]) - abs(0.15 * min(d1[["x"]])),
                max(d1[["x"]]) + abs(0.15 * max(d1[["x"]])),
                max(d1[["x"]]) + abs(0.15 * max(d1[["x"]]))
              ),
              "y" = c(
                min(d1[["y"]]) - abs(0.15 * min(d1[["y"]])),
                max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
                max(d1[["y"]]) + abs(0.15 * max(d1[["y"]])),
                min(d1[["y"]]) - abs(0.15 * min(d1[["y"]]))
              ),
              "pw" = i
            )
            return(d2) # nolint
          }
        )
      )
      npw[["pw"]] <- factor(
        npw[["pw"]],
        levels = c(
          "Phospholipid Biosynthesis", "Fatty Acid Biosynthesis",
          "Lipid Transport", "Plasmalogen Biosynthesis",
          "Oxylipin Biosynthesis", "Sterol Lipid Biosynthesis",
          "Cholesterol Catabolism", "Sphingolipid Biosynthesis",
          "Glycerolipid Biosynthesis"
        )
      )
      # Node box color to denote significant clusters
      npl_box_color <- npl[grepl("FDR", names(npl))]
      npl_box_color[is.na(npl_box_color)] <- 1
      npl[["box_color"]] <- unlist(lapply(
        seq.int(1, nrow(npl_box_color), 1),
        function(i) {
          min(npl_box_color[i, ]) < 0.05
        }
      ))
      # Node attributes
      np_nodes <- setNames(
        lapply(
          c("Sat", "Unsat", ""),
          function(j) {
            dnode <- data.frame(
              "x" = npl[["x"]],
              "y" = npl[["y"]],
              "size" = ifelse(
                is.na(npl[[paste(
                  "n", cmp, j, sep = "_"
                )]]) |
                  unlist(
                    lapply(
                      npl[[paste(
                        "n", cmp, j, sep = "_"
                      )]],
                      function(x) is.null(x)
                    )
                  ),
                0,
                sqrt(as.numeric(unlist(npl[[paste(
                  "n", cmp, j, sep = "_"
                )]])))
              ),
              "fill" = ifelse(
                is.na(npl[[paste(
                  "Ratio", cmp, j, sep = "_"
                )]]) |
                  unlist(
                    lapply(
                      npl[[paste(
                        "Ratio", cmp, j, sep = "_"
                      )]],
                      function(x) is.null(x)
                    )
                  ),
                0.5,
                unlist(npl[[paste(
                  "Ratio", cmp, j, sep = "_"
                )]])
              ),
              "color" = ifelse(
                is.na(npl[[paste(
                  "Ratio", cmp, j, sep = "_"
                )]]) |
                  unlist(
                    lapply(
                      npl[[paste(
                        "Ratio", cmp, j, sep = "_"
                      )]],
                      function(x) is.null(x)
                    )
                  ),
                "b",
                "a"
              ),
              "lab" = ifelse(
                unlist(
                  lapply(
                    npl[[paste("n", cmp, j, sep = "_")]],
                    function(x) is.null(x)
                  )
                ),
                "",
                j
              ),
              "lab_FDR" = unlist(
                lapply(
                  npl[[paste("FDR", cmp, j, sep = "_")]],
                  function(x) {
                    d1 <- ifelse(
                      !is.null(x),
                      x > 0.05 | is.na(x),
                      TRUE
                    )
                    d1 <- ifelse(
                      d1 == FALSE,
                      paste("FDR = ", round(x, digits = 4)),
                      ""
                    )
                    return(d1) # nolint
                  }
                )
              ),
              "lab_size" = ifelse(
                npl[["cluster_size"]] == 0,
                0,
                1.5
              )
            )
            dnode <- dnode[dnode[["size"]] > 0, ]
            return(dnode) # nolint
          }
        ),
        c("Sat", "Unsat", "")
      )
      # Plot base network
      np_base <- ggraph::ggraph(npl) +
        # color scheme
        ggplot2::scale_color_manual(
          "Pathway",
          values = col_univ() # nolint
        ) +
        ggplot2::scale_fill_manual(
          "Pathway",
          values = col_univ()
        ) +
        # Subclass shading
        ggplot2::geom_polygon(
          data = npw,
          ggplot2::aes(
            x = .data[["x"]], # nolint
            y = .data[["y"]],
            fill = .data[["pw"]]
          ),
          color = "grey25",
          alpha = 1
        ) +
        # edge attributes
        ggraph::geom_edge_link(
          ggplot2::aes(
            label = ifelse(
              .data[["set_alpha_edge"]] == 0.25, # nolint
              "",
              .data[["enzyme.id"]]
            ),
            alpha = .data[["set_alpha_edge"]]
          ),
          label_dodge = ggplot2::unit(2, "mm"),
          alpha = 0.5,
          label_alpha = 0.0,
          angle_calc = "along",
          color = "grey50",
          show.legend = FALSE
        ) +
        ggnewscale::new_scale_fill() +
        # Background for node panels
        ggplot2::geom_rect(
          ggplot2::aes(
            fill = .data[["box_color"]],
            xmin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x - 0.35 # nolint
            ),
            ymin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y - 0.35 # nolint
            ),
            ymax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y + 0.25
            ),
            xmax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x + 0.35
            )
          ),
          alpha = 0.9,
          color = "grey25",
          show.legend = FALSE
        ) +
        ggplot2::scale_fill_manual(
          "Significant",
          values = c("grey", "goldenrod1")
        )
      # Add nodes based on saturation
      np_enr_nodes <- np_base +
        # node points
        ggraph::geom_node_point(
          ggplot2::aes(
            alpha = ifelse(
              .data[["set_alpha"]] == 0, # nolint
              1,
              0
            )
          ),
          color = "grey75",
          show.legend = FALSE
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggnewscale::new_scale_fill() +
        ## Enrichment nodes
        ## Saturated lipids
        ggraph::geom_node_point(
          data = np_nodes[["Sat"]],
          ggplot2::aes(
            x = np_nodes[["Sat"]][["x"]],
            y = np_nodes[["Sat"]][["y"]],
            size = np_nodes[["Sat"]][["size"]],
            fill = np_nodes[["Sat"]][["fill"]],
            color = np_nodes[["Sat"]][["color"]]
          ),
          position = ggplot2::position_nudge(
            x = -0.25,
            y = -0.1
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggraph::geom_node_point(
          data = np_nodes[["Unsat"]],
          ggplot2::aes(
            x = np_nodes[["Unsat"]][["x"]],
            y = np_nodes[["Unsat"]][["y"]],
            size = np_nodes[["Unsat"]][["size"]],
            fill = np_nodes[["Unsat"]][["fill"]],
            color = np_nodes[["Unsat"]][["color"]]
          ),
          position = ggplot2::position_nudge(
            x = 0.25,
            y = -0.1
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggraph::geom_node_point(
          data = np_nodes[[3]],
          ggplot2::aes(
            x = np_nodes[[3]][["x"]],
            y = np_nodes[[3]][["y"]],
            size = np_nodes[[3]][["size"]],
            fill = np_nodes[[3]][["fill"]],
            color = np_nodes[[3]][["color"]]
          ),
          position = ggplot2::position_nudge(
            x = 0,
            y = -0.1
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggplot2::scale_color_manual(
          "Pathway",
          values = c("black", "white")
        )
      # Add node labels
      np_enr_labs <- np_enr_nodes +
        ggnewscale::new_scale_color() +
        # ChemRICH node labels
        ## Saturated
        shadowtext::geom_shadowtext(
          data = np_nodes[["Sat"]],
          ggplot2::aes(
            x = np_nodes[["Sat"]][["x"]],
            y = np_nodes[["Sat"]][["y"]],
            label = np_nodes[["Sat"]][["lab"]],
            size = np_nodes[["Sat"]][["lab_size"]]
          ),
          nudge_x = -0.25,
          nudge_y = -0.2,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        ## Unsaturated
        shadowtext::geom_shadowtext(
          data = np_nodes[["Unsat"]],
          ggplot2::aes(
            x = np_nodes[["Unsat"]][["x"]],
            y = np_nodes[["Unsat"]][["y"]],
            label = np_nodes[["Unsat"]][["lab"]],
            size = np_nodes[["Unsat"]][["lab_size"]]
          ),
          nudge_x = 0.25,
          nudge_y = -0.2,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        ## No saturation
        shadowtext::geom_shadowtext(
          data = np_nodes[[3]],
          ggplot2::aes(
            x = np_nodes[[3]][["x"]],
            y = np_nodes[[3]][["y"]],
            label = np_nodes[[3]][["lab"]],
            size = np_nodes[[3]][["lab_size"]]
          ),
          nudge_x = 0,
          nudge_y = -0.2,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        # text labels
        ggrepel::geom_text_repel(
          ggplot2::aes(
            x = .data[["x"]],
            y = .data[["y"]],
            label = .data[["label"]],
            alpha = ifelse(
              .data[["cluster_size"]] == 0,
              0.1,
              1
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0.05,
              2
            )
          ),
          color = "white",
          bg.r = 0.03,
          bg.color = "grey10",
          nudge_x = 0,
          nudge_y = 0.1 * 1,
          show.legend = FALSE
        )
      # Add theme
      np_enr_thm <- np_enr_labs +
        ggplot2::scale_fill_gradientn(
          "Increased Ratio",
          colors = c(
            "dodgerblue4",
            "azure",
            "firebrick3"
          )
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggplot2::scale_size_area(
          max_size = 10
        ) +
        ggplot2::scale_color_manual(
          "Pathway",
          values = col_univ()
        ) +
        # plot theme
        gen_theme() + # nolint
        net_theme() # nolint

      ggplot2::ggsave(
        "net_enr_SNNvLNN_cells.png",
        np_enr_thm,
        width = 15,
        height = 10,
        dpi = 500
      )
    }
  }

  # Lipid class ratios
  if(net_type == "class_comp") { # nolint
    net1 <- d_enrch
    cl_var1 <- cl_var
    cmp <- comp1

    ## Adjust node attributes
    net_anno_node <- net_plot_rat[net_plot_rat[["comp_type"]] == "node", ]
    net_anno_node[[cl_var1]] <- paste(
      net_anno_node[["class1"]],
      net_anno_node[["class2"]],
      sep = "_"
    )
    net_anno <- dplyr::left_join(
      net1,
      net_anno_node,
      by = cl_var1
    )
    net_anno <- net_anno[
      !apply(net_anno, 1, function(x) any(is.na(x))),
    ]
    net_enrch <- tidyr::pivot_wider(
      net_anno[, c( # nolint
        "Comparison", "label",
        "Log2FC", "FDR"
      )],
      names_from = c(.data[["Comparison"]]), # nolint
      values_from = c(.data[["Log2FC"]], .data[["FDR"]])
    )
    names(net_nodes)
    net_nodes <- dplyr::left_join(
      net_nodes,
      net_enrch,
      by = "label"
    )
    net_nodes[["cluster_size"]] <- ifelse(
      unlist(
        lapply(
          apply(
            net_nodes[, 12:ncol(net_nodes)],
            1,
            function(x) unlist(x)
          ),
          function(y) is.null(y)
        )
      ),
      0,
      1
    )
    net_nodes[["set_alpha"]] <- net_nodes[["cluster_size"]]
    ## Adjust edge attributes
    net_anno_edge <- net_plot_rat[net_plot_rat[["comp_type"]] == "edge", ]
    net_anno_edge[["Name"]] <- paste(
      net_anno_edge[["class1"]],
      net_anno_edge[["class2"]],
      sep = "_"
    )
    net_anno_edge <- dplyr::left_join(
      net1,
      net_anno_edge,
      by = cl_var1
    )
    net_anno_edge <- net_anno_edge[
      !apply(net_anno_edge, 1, function(x) any(is.na(x))),
    ]
    net_anno_edge[["from"]] <- as.data.frame(
      t(
        as.data.frame(
          strsplit(net_anno_edge[["label"]], "_")
        )
      )
    )[[1]]
    net_anno_edge[["to"]] <- as.data.frame(
      t(
        as.data.frame(
          strsplit(net_anno_edge[["label"]], "_")
        )
      )
    )[[2]]
    net_anno_edge[["Saturation"]] <- ifelse(
      grepl("Uns|uns", net_anno_edge[[cl_var1]]),
      "Unsat",
      "Sat"
    )
    net_enrch_edge <- tidyr::pivot_wider(
      net_anno_edge[, c( # nolint
        "Comparison", "from", "to", "Saturation",
        "Log2FC", "FDR"
      )],
      names_from = c(.data[["Comparison"]], .data[["Saturation"]]), # nolint
      values_from = c(.data[["Log2FC"]], .data[["FDR"]])
    )
    net_edges <- dplyr::left_join(
      net_edges,
      net_enrch_edge,
      by = c("from", "to")
    )
    net_edges[["set_alpha_edge"]] <- ifelse(
      apply(
        net_edges[, 10:ncol(net_edges)],
        1,
        function(x) any(!is.na(x))
      ),
      1,
      0.25
    )
    if( # nolint
      paste("Log2FC", cmp, "Sat", sep = "_") %in%
        names(net_edges)
    ) {
      net_edges[["sat_col"]] <- ifelse(
        is.na(net_edges[[paste(
          "Log2FC", cmp, "Sat", sep = "_"
        )]]) |
          unlist(
            lapply(
              net_edges[[paste(
                "Log2FC", cmp, "Sat", sep = "_"
              )]],
              function(x) is.null(x)
            )
          ),
        0,
        unlist(net_edges[[paste(
          "Log2FC", cmp, "Sat", sep = "_"
        )]])
      )
      net_edges[["sat_col"]] <- ifelse(
        net_edges[["sat_col"]] < 0,
        "dodgerblue4",
        ifelse(net_edges[["sat_col"]] > 0, "firebrick3", "white")
      )
    }
    if( # nolint
      paste("Log2FC", cmp, "Unsat", sep = "_") %in%
        names(net_edges)
    ) {
      net_edges[["unsat_col"]] <- ifelse(
        is.na(net_edges[[paste(
          "Log2FC", cmp, "Unsat", sep = "_"
        )]]) |
          unlist(
            lapply(
              net_edges[[paste(
                "Log2FC", cmp, "Unsat", sep = "_"
              )]],
              function(x) is.null(x)
            )
          ),
        0,
        unlist(net_edges[[paste(
          "Log2FC", cmp, "Unsat", sep = "_"
        )]])
      )
      net_edges[["unsat_col"]] <- ifelse(
        net_edges[["unsat_col"]] < 0,
        "dodgerblue4",
        ifelse(net_edges[["unsat_col"]] > 0, "firebrick3", "white")
      )
    }
    ## Network
    net_plot <- igraph::graph_from_data_frame(
      net_edges,
      vertices = net_nodes
    )
    ## Network layout
    net_plot_lay <- ggraph::create_layout(net_plot, layout = "stress")
    net_plot_lay[["x"]] <- net_plot_lay[["x_man"]]
    net_plot_lay[["y"]] <- net_plot_lay[["y_man"]]
    # Plot
    if("sat_col" %in% names(net_edges) == FALSE && "unsat_col" %in% names(net_edges)) { # nolint
      net_plot2 <- ggraph::ggraph(
        net_plot_lay
      ) +
        ggplot2::scale_fill_manual(
          "Pathway",
          values = col_univ() # nolint
        ) +
        # Boundary polygon for distinguishing different pathways
        ggplot2::geom_polygon(
          data = net_plot_lay2,
          ggplot2::aes(
            x = net_plot_lay2[["x"]],
            y = net_plot_lay2[["y"]],
            fill = net_plot_lay2[["synthesis_pathway"]]
          ),
          alpha = 0.5,
          color = "grey25",
          show.legend = FALSE
        ) +
        ## Color scale for edges
        ggplot2::scale_color_manual(
          "Log2FC",
          values = c("dodgerblue4", "white", "firebrick3")
        ) +
        ## Unsaturated lipid class links
        ggraph::geom_edge_link(
          ggplot2::aes(
            edge_alpha = ifelse(
              .data[["set_alpha_edge"]] == 0.25 | # nolint
                .data[["unsat_col"]] == "white", # nolint
              0,
              .data[["set_alpha_edge"]]
            ),
            edge_color = .data[["unsat_col"]],
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, "Unsat", sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x), # nolint
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            )
          ),
          position = ggplot2::position_nudge(
            x = 0.01,
            y = -0.04
          ),
          edge_linetype = "solid",
          edge_width = 1.25,
          end_cap = ggraph::circle(5, "mm"),
          lineend = "round",
          arrow = grid::arrow(
            length = ggplot2::unit(2, "mm"),
            type = "closed"
          ),
          angle_calc = "along",
          label_dodge = ggplot2::unit(-1.4, "mm"),
          label_alpha = 0.8,
          show.legend = FALSE
        ) +
        # general edge attributes
        ggraph::geom_edge_link(
          ggplot2::aes(
            label = ifelse(
              .data[["set_alpha_edge"]] == 0.25, # nolint
              "",
              .data[["enzyme_id"]]
            ),
            alpha = .data[["set_alpha_edge"]]
          ),
          edge_linetype = "solid",
          label_dodge = ggplot2::unit(1.2, "mm"),
          label_alpha = 0.6,
          angle_calc = "along",
          color = "grey50",
          show.legend = FALSE
        ) +
        # Background for node panels
        ggplot2::geom_rect(
          ggplot2::aes(
            xmin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x - 0.175 # nolint
            ),
            ymin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y - 0.175 # nolint
            ),
            ymax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y + 0.175
            ),
            xmax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x + 0.175
            )
          ),
          alpha = 0.7,
          fill = "grey",
          color = "grey25",
          show.legend = FALSE
        ) +
        # node points
        ggraph::geom_node_point(
          ggplot2::aes(
            alpha = ifelse(
              .data[["set_alpha"]] == 0, # nolint
              1,
              0
            )
          ),
          color = "grey75",
          show.legend = FALSE
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggnewscale::new_scale_fill() +
        # Enrichment nodes
        ggraph::geom_node_point(
          ggplot2::aes(
            size = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0,
              1
            ),
            fill = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0.5,
              unlist(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]])
            ),
            color = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              "b",
              "a"
            )
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggplot2::scale_color_manual(
          "Pathway",
          values = c("black", "white")
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        # ChemRICH node labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = ifelse(
              unlist(
                lapply(
                  .data[[paste("Log2FC", cmp, sep = "_")]],
                  function(x) is.null(x)
                )
              ),
              "",
              "Sat./Unsat."
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.05
            )
          ),
          nudge_y = -0.075,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        # ChemRICH node FDR labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x),
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.05
            )
          ),
          nudge_y = -0.125,
          color = "white",
          bg.color = "grey10",
          show.legend = FALSE
        ) +
        # Increased ratio color scale
        ggplot2::scale_fill_gradientn(
          "Log2FC",
          colors = c(
            "dodgerblue4",
            "azure",
            "firebrick3"
          )
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggplot2::scale_size_area(
          max_size = 16
        ) +
        # text labels
        ggrepel::geom_text_repel(
          ggplot2::aes(
            x = .data[["x"]],
            y = .data[["y"]],
            label = .data[["label"]],
            alpha = ifelse(
              .data[["cluster_size"]] == 0,
              0.1,
              1
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0.02,
              0.05
            )
          ),
          color = "black",
          bg.r = 0.01,
          bg.color = "white",
          nudge_x = 0,
          nudge_y = 0.09 * 1,
          show.legend = FALSE
        ) +
        # plot theme
        ms_theme1() + # nolint
        ms_theme_net() # nolint
    }
    if("unsat_col" %in% names(net_edges) == FALSE && "sat_col" %in% names(net_edges)) { # nolint
      net_plot2 <- ggraph::ggraph(
        net_plot_lay
      ) +
        ggplot2::scale_fill_manual(
          "Pathway",
          values = col_univ() # nolint
        ) +
        # Boundary polygon for distinguishing different pathways
        ggplot2::geom_polygon(
          data = net_plot_lay2,
          ggplot2::aes(
            x = net_plot_lay2[["x"]],
            y = net_plot_lay2[["y"]],
            fill = net_plot_lay2[["synthesis_pathway"]]
          ),
          alpha = 0.5,
          color = "grey25",
          show.legend = FALSE
        ) +
        ## Color scale for edges
        ggplot2::scale_color_manual(
          "Log2FC",
          values = c("dodgerblue4", "white", "firebrick3")
        ) +
        ## Saturated lipid class links
        ggraph::geom_edge_link(
          ggplot2::aes(
            edge_alpha = ifelse(
              .data[["set_alpha_edge"]] == 0.25 | # nolint
                .data[["sat_col"]] == "white", # nolint
              0,
              .data[["set_alpha_edge"]]
            ),
            edge_color = .data[["sat_col"]],
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, "Sat", sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x), # nolint
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            )
          ),
          position = ggplot2::position_nudge(
            x = -0.03,
            y = 0.06
          ),
          edge_linetype = "twodash",
          edge_width = 1.25,
          end_cap = ggraph::circle(5, "mm"),
          lineend = "round",
          arrow = grid::arrow(
            length = ggplot2::unit(2, "mm"),
            type = "closed"
          ),
          angle_calc = "along",
          label_dodge = ggplot2::unit(1.4, "mm"),
          label_alpha = 0.8,
          show.legend = FALSE
        ) +
        # general edge attributes
        ggraph::geom_edge_link(
          ggplot2::aes(
            label = ifelse(
              .data[["set_alpha_edge"]] == 0.25, # nolint
              "",
              .data[["enzyme_id"]]
            ),
            alpha = .data[["set_alpha_edge"]]
          ),
          edge_linetype = "solid",
          label_dodge = ggplot2::unit(1.2, "mm"),
          label_alpha = 0.6,
          angle_calc = "along",
          color = "grey50",
          show.legend = FALSE
        ) +
        # Background for node panels
        ggplot2::geom_rect(
          ggplot2::aes(
            xmin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x - 0.175 # nolint
            ),
            ymin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y - 0.175 # nolint
            ),
            ymax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y + 0.175
            ),
            xmax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x + 0.175
            )
          ),
          alpha = 0.7,
          fill = "grey",
          color = "grey25",
          show.legend = FALSE
        ) +
        # node points
        ggraph::geom_node_point(
          ggplot2::aes(
            alpha = ifelse(
              .data[["set_alpha"]] == 0, # nolint
              1,
              0
            )
          ),
          color = "grey75",
          show.legend = FALSE
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggnewscale::new_scale_fill() +
        # Enrichment nodes
        ggraph::geom_node_point(
          ggplot2::aes(
            size = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0,
              1
            ),
            fill = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0.5,
              unlist(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]])
            ),
            color = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              "b",
              "a"
            )
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggplot2::scale_color_manual(
          "Pathway",
          values = c("black", "white")
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        # ChemRICH node labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = ifelse(
              unlist(
                lapply(
                  .data[[paste("Log2FC", cmp, sep = "_")]],
                  function(x) is.null(x)
                )
              ),
              "",
              "Sat./Unsat."
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.05
            )
          ),
          nudge_y = -0.075,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        # ChemRICH node FDR labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x),
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.05
            )
          ),
          nudge_y = -0.125,
          color = "white",
          bg.color = "grey10",
          show.legend = FALSE
        ) +
        # Increased ratio color scale
        ggplot2::scale_fill_gradientn(
          "Log2FC",
          colors = c(
            "dodgerblue4",
            "azure",
            "firebrick3"
          )
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggplot2::scale_size_area(
          max_size = 16
        ) +
        # text labels
        ggrepel::geom_text_repel(
          ggplot2::aes(
            x = .data[["x"]],
            y = .data[["y"]],
            label = .data[["label"]],
            alpha = ifelse(
              .data[["cluster_size"]] == 0,
              0.1,
              1
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0.02,
              0.05
            )
          ),
          color = "black",
          bg.r = 0.01,
          bg.color = "white",
          nudge_x = 0,
          nudge_y = 0.09 * 1,
          show.legend = FALSE
        ) +
        # plot theme
        ms_theme1() + # nolint
        ms_theme_net() # nolint
    }
    if("sat_col" %in% names(net_edges) && "unsat_col" %in% names(net_edges)) { # nolint
      net_plot2 <- ggraph::ggraph(
        net_plot_lay
      ) +
        ggplot2::scale_fill_manual(
          "Pathway",
          values = col_univ() # nolint
        ) +
        # Boundary polygon for distinguishing different pathways
        ggplot2::geom_polygon(
          data = net_plot_lay2,
          ggplot2::aes(
            x = net_plot_lay2[["x"]],
            y = net_plot_lay2[["y"]],
            fill = net_plot_lay2[["synthesis_pathway"]]
          ),
          alpha = 0.5,
          color = "grey25",
          show.legend = FALSE
        ) +
        ## Color scale for edges
        ggplot2::scale_color_manual(
          "Log2FC",
          values = c("dodgerblue4", "white", "firebrick3")
        ) +
        ## Saturated lipid class links
        ggraph::geom_edge_link(
          ggplot2::aes(
            edge_alpha = ifelse(
              .data[["set_alpha_edge"]] == 0.25 | # nolint
                .data[["sat_col"]] == "white", # nolint
              0,
              .data[["set_alpha_edge"]]
            ),
            edge_color = .data[["sat_col"]],
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, "Sat", sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x), # nolint
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            )
          ),
          position = ggplot2::position_nudge(
            x = -0.03,
            y = 0.06
          ),
          edge_linetype = "twodash",
          edge_width = 1.25,
          end_cap = ggraph::circle(5, "mm"),
          lineend = "round",
          arrow = grid::arrow(
            length = ggplot2::unit(2, "mm"),
            type = "closed"
          ),
          angle_calc = "along",
          label_dodge = ggplot2::unit(1.4, "mm"),
          label_alpha = 0.8,
          show.legend = FALSE
        ) +
        ## Unsaturated lipid class links
        ggraph::geom_edge_link(
          ggplot2::aes(
            edge_alpha = ifelse(
              .data[["set_alpha_edge"]] == 0.25 | # nolint
                .data[["unsat_col"]] == "white", # nolint
              0,
              .data[["set_alpha_edge"]]
            ),
            edge_color = .data[["unsat_col"]],
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, "Unsat", sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x),
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            )
          ),
          position = ggplot2::position_nudge(
            x = 0.01,
            y = -0.04
          ),
          edge_linetype = "solid",
          edge_width = 1.25,
          end_cap = ggraph::circle(5, "mm"),
          lineend = "round",
          arrow = grid::arrow(
            length = ggplot2::unit(2, "mm"),
            type = "closed"
          ),
          angle_calc = "along",
          label_dodge = ggplot2::unit(-1.4, "mm"),
          label_alpha = 0.8,
          show.legend = FALSE
        ) +
        # general edge attributes
        ggraph::geom_edge_link(
          ggplot2::aes(
            label = ifelse(
              .data[["set_alpha_edge"]] == 0.25, # nolint
              "",
              .data[["enzyme_id"]]
            ),
            alpha = .data[["set_alpha_edge"]]
          ),
          edge_linetype = "solid",
          label_dodge = ggplot2::unit(1.2, "mm"),
          label_alpha = 0.6,
          angle_calc = "along",
          color = "grey50",
          show.legend = FALSE
        ) +
        # Background for node panels
        ggplot2::geom_rect(
          ggplot2::aes(
            xmin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x - 0.175 # nolint
            ),
            ymin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y - 0.175 # nolint
            ),
            ymax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y + 0.175
            ),
            xmax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x + 0.175
            )
          ),
          alpha = 0.7,
          fill = "grey",
          color = "grey25",
          show.legend = FALSE
        ) +
        # node points
        ggraph::geom_node_point(
          ggplot2::aes(
            alpha = ifelse(
              .data[["set_alpha"]] == 0, # nolint
              1,
              0
            )
          ),
          color = "grey75",
          show.legend = FALSE
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggnewscale::new_scale_fill() +
        # Enrichment nodes
        ggraph::geom_node_point(
          ggplot2::aes(
            size = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0,
              1
            ),
            fill = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0.5,
              unlist(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]])
            ),
            color = ifelse(
              is.na(.data[[paste(
                "Log2FC", cmp, sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Log2FC", cmp, sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              "b",
              "a"
            )
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggplot2::scale_color_manual(
          "Pathway",
          values = c("black", "white")
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        # ChemRICH node labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = ifelse(
              unlist(
                lapply(
                  .data[[paste("Log2FC", cmp, sep = "_")]],
                  function(x) is.null(x)
                )
              ),
              "",
              "Sat./Unsat."
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.05
            )
          ),
          nudge_y = -0.075,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        # ChemRICH node FDR labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x),
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.05
            )
          ),
          nudge_y = -0.125,
          color = "white",
          bg.color = "grey10",
          show.legend = FALSE
        ) +
        # Increased ratio color scale
        ggplot2::scale_fill_gradientn(
          "Log2FC",
          colors = c(
            "dodgerblue4",
            "azure",
            "firebrick3"
          )
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggplot2::scale_size_area(
          max_size = 16
        ) +
        # text labels
        ggrepel::geom_text_repel(
          ggplot2::aes(
            x = .data[["x"]],
            y = .data[["y"]],
            label = .data[["label"]],
            alpha = ifelse(
              .data[["cluster_size"]] == 0,
              0.1,
              1
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0.02,
              0.05
            )
          ),
          color = "black",
          bg.r = 0.01,
          bg.color = "white",
          nudge_x = 0,
          nudge_y = 0.09 * 1,
          show.legend = FALSE
        ) +
        # plot theme
        ms_theme1() + # nolint
        ms_theme_net() # nolint
    }
  }
  return(net_plot2)
}

#' Scatter Plot
#'
#' Generates a scatter plot from a statistical results object for
#' a chosen comparison.
#'
#' @param df1 Input data frame.
#' @param type1 Scatter plot type (either "std" or "oxview").
#' If type is "oxview," a variable indicating either "Oxidized"
#' or "Unoxidized" lipids must be present in the input data frame.
#' @param xvar X-axis variable.
#' @param yvar Y-axis variable.
#' @param clvar Group variable.
#' @param oxvar (optional) If type is "oxview," the variable name
#' distinguishing oxidized from unoxidized lipids.
#' @param bns (optional) Bin number for scatter plot types using
#' stat_density_2d().
#' @return A scatter plot for the chosen treatment comparisons.
#' @examples
#'
#' # ms_plot_scatter(
#' #   df1 = dox,
#' #   type1 = "oxview",
#' #   xvar = "rt",
#' #   yvar = "mz",
#' #   clvar = "class"
#' # )
#'
#' @export
ms_plot_scatter <- function(
  df1,
  type1,
  xvar,
  yvar,
  clvar,
  oxvar = "ox",
  bns = 50
) {
  d <- df1
  if(type1 == "oxview") { # nolint
    ggplot2::ggplot(
      d,
      ggplot2::aes(
        x = .data[[xvar]], # nolint
        y = .data[[yvar]],
        color = .data[[clvar]],
        label = .data[[clvar]]
      )
    ) +
      ggplot2::scale_fill_manual(
        name = "Type",
        values = rep(
          col_univ()[[2]],
          length(unique(d[d[[oxvar]] == "Unoxidized", ][[clvar]]))
        )
      ) +
      ggplot2::stat_density_2d(
        data = d[d[[oxvar]] == "Unoxidized", ],
        ggplot2::aes(
          fill = d[d[[oxvar]] == "Unoxidized", ][[clvar]]
        ),
        geom = "polygon",
        alpha = 0.1,
        linewidth = 0.01,
        bins = bns,
        contour = TRUE,
        show.legend = FALSE
      ) +
      ggnewscale::new_scale_fill() +
      ggplot2::scale_fill_manual(
        name = "Type",
        values = rep(
          col_univ()[[1]],
          length(unique(d[d[[oxvar]] == "Oxidized", ][[clvar]]))
        )
      ) +
      ggplot2::stat_density_2d(
        data = d[d[[oxvar]] == "Oxidized", ],
        ggplot2::aes(
          fill = d[d[[oxvar]] == "Oxidized", ][[clvar]]
        ),
        geom = "polygon",
        alpha = 0.4,
        linewidth = 0.01,
        bins = bns,
        contour = TRUE,
        show.legend = FALSE
      ) +
      ggnewscale::new_scale_fill() +
      ggplot2::scale_color_manual(
        name = "Class",
        values = col_univ()
      ) +
      ggplot2::geom_point(
        shape = 16,
        size = 1,
        alpha = 0.6
      ) +
      ggrepel::geom_text_repel(
        data = setNames(
          aggregate(
            d[, c(yvar, xvar)],
            list(d[[clvar]]),
            FUN = median
          ),
          c(clvar, yvar, xvar
          )
        ),
        size = 3,
        bg.color = "grey0",
        color = "white",
        bg.r = 0.05
      ) +
      # Add Theme
      ms_theme1() + # nolint
      ggplot2::labs(
        y = "m/z",
        x = "RT (min.)",
        color = "Class"
      ) +
      ggplot2::theme(
        plot.margin = ggplot2::unit(
          c(
            0.1,
            0.1,
            0.1,
            0.1
          ),
          "cm"
        )
      )
  }
}
