#' Lipid Network Circular Node Panel
#'
#' Extension of hive_mult() for isolating node panels for custom
#' figure design. Node colors represent the
#' fold change for the specified comparison for individual lipid
#' species. See HiVE example data for more details.
#' Note that this function is intended for manually plotting data
#' onto a network generated by hive_base().
#'
#' @param stat_obj A data frame of statistical results containing
#' fold changes and p-values or a Seurat object. The labels must match
#' nodes from the HiVE base network nodes to properly function. Example
#' data are included for formatting help. Can also plot differential
#' gene expression or general expression data if desired.
#' @param name_node Name of the node to plot.
#' @param col_fc Fold change column name.
#' @param col_p p value column name.
#' @param col_lab Label column for mapping input data onto HiVE nodes.
#' @param tx_size_major Major node label text size.
#' @param tx_size_minor Minor node label text size.
#' @param p_size Minor node point size.
#'
#' @return A ggplot2 object plotting circular node points for a specific
#' HiVE node.
#' @examples
#'
#' # ## Annotation count network
#' # hive_panel_node(stat_obj = d1, name_node = "HETE")
#'
#' @export
hive_panel_node <- function(
  stat_obj,
  name_node,
  col_fc = "Log2FC",
  col_p = "p.adj",
  col_lab = "label",
  tx_size_major = 4,
  tx_size_minor = 3,
  p_size = 5
) {
  # Load data
  net1 <- stat_obj
  # return matches for each node from input stats
  np1 <- net1[net1[[col_lab]] == name_node, ]
  # calculate x-y coordinates around origin
  ## define function for plotting points around central node
  fun_coord <- function(h, k, r, n) {
    ang1 <- (2 * pi) / n
    d_out <- dplyr::bind_rows(
      lapply(
        seq.int(1, n, 1),
        function(i) {
          theta <- i * ang1
          data.frame(
            "x" = h + r * cos(theta),
            "y" = k + r * sin(theta)
          )
        }
      )
    )
    return(d_out) # nolint
  }
  if (nrow(np1) == 1) {
    np1 <- cbind(np1, data.frame("x" = 0, "y" = 0))
  }
  if (nrow(np1) == 2) {
    np1 <- cbind(
      np1,
      data.frame(
        "x" = c(0 - 0.2, 0 + 0.2),
        "y" = c(0, 0)
      )
    )
  }
  if (nrow(np1) >= 3) {
    np1 <- cbind(np1, fun_coord(0, 0, 0.2, nrow(np1)))
  }
  # Set node size and color to emphasize
  # significant points
  np1[["size"]] <- ifelse(np1[[col_p]] < 0.05, 2, 1.5)
  np1[["col.node"]] <- ifelse(np1[[col_p]] < 0.05, "a", "b")
  # Scale fold change from 0 to 1 for node fill
  np1[["fill.node"]] <- (
    np1[[col_fc]] - min(np1[[col_fc]], na.rm = TRUE)
  ) / (
    max(np1[[col_fc]], na.rm = TRUE) -
      min(np1[[col_fc]], na.rm = TRUE)
  )
  np1[["fill.node"]] <- ifelse(
    np1[[col_fc]] == 0, 0.5,
    np1[["fill.node"]]
  )
  ### define color scale
  col_fun <- colorRampPalette(col_grad(scm = 5))
  col_len <- col_fun(length(np1[["fill.node"]]))
  np1[["fill.node.names"]] <- col_len
  if (length(np1[["fill.node"]]) == 1 && np1[[col_fc]] < 1) {
    np1[["fill.node"]] <- col_grad(scm = 5)[[1]]
  }
  if (length(np1[["fill.node"]]) == 1 && np1[[col_fc]] > 1) {
    np1[["fill.node"]] <- col_grad(scm = 5)[[3]]
  }
  # Plot
  if (length(np1[["fill.node"]]) == 1) {
    np2 <- ggplot2::ggplot(data = np1) +
      # Background circle
      ggforce::geom_circle(
        ggplot2::aes(
          x0 = 0,
          y0 = 0,
          r = 0.3
        ),
        color = "grey25",
        fill = "grey",
        show.legend = FALSE,
        alpha = 0.9
      ) +
      # node points
      ggraph::geom_node_point(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]]
        ),
        shape = 21,
        size = p_size,
        fill = np1[["fill.node"]],
        color = "black",
        show.legend = FALSE
      ) +
      # Primary node labels
      ggplot2::geom_label(
        ggplot2::aes(
          x = 0,
          y = 0,
          label = .data[[col_lab]]
        ),
        alpha = 1,
        linewidth = 0.15,
        nudge_y = 0.3,
        size = tx_size_major,
        show.legend = FALSE
      ) +
      # Individual node labels
      shadowtext::geom_shadowtext(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]],
          label = .data[["Name"]]
        ),
        nudge_y = 0.05,
        size = tx_size_minor,
        color = "white",
        bg.color = "grey25",
        show.legend = FALSE
      ) +
      ggplot2::scale_linewidth(
        range = c(0, 0.15)
      ) +
      # plot theme
      gen_theme() + # nolint
      net_theme() # nolint
  }
  if (length(np1[["fill.node"]]) > 1) {
    np2 <- ggplot2::ggplot(data = np1) +
      # Background circle
      ggforce::geom_circle(
        ggplot2::aes(
          x0 = 0,
          y0 = 0,
          r = 0.3
        ),
        color = "grey25",
        fill = "grey",
        show.legend = FALSE,
        alpha = 0.9
      ) +
      # node points
      ggraph::geom_node_point(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]],
          fill = .data[["fill.node"]]
        ),
        shape = 21,
        size = p_size,
        color = "black",
        show.legend = FALSE
      ) +
      ggplot2::scale_fill_continuous(
        palette = col_grad(scm = 5)
      ) +
      # Primary node labels
      ggplot2::geom_label(
        ggplot2::aes(
          x = 0,
          y = 0,
          label = .data[[col_lab]]
        ),
        alpha = 1,
        linewidth = 0.15,
        nudge_y = 0.3,
        size = tx_size_major,
        show.legend = FALSE
      ) +
      # Individual node labels
      shadowtext::geom_shadowtext(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]],
          label = .data[["Name"]]
        ),
        nudge_y = 0.05,
        size = tx_size_minor,
        color = "white",
        bg.color = "grey25",
        show.legend = FALSE
      ) +
      ggplot2::scale_linewidth(
        range = c(0, 0.15)
      ) +
      # plot theme
      gen_theme() + # nolint
      net_theme() # nolint
  }
  return(np2) # nolint
}

#' Lipid Network Edge Panel
#'
#' Extension of hive_mult() for isolating edge panels for custom
#' figure design. Edge box colors represent the
#' fold change for the specified comparison for individual lipid
#' genes. See HiVE example data for more details.
#' Note that this function is intended for manually plotting data
#' onto a network generated by hive_base().
#'
#' @param stat_obj A data frame of statistical results containing
#' fold changes and p-values or a Seurat object. The labels must match
#' nodes from the HiVE base network nodes to properly function. Example
#' data are included for formatting help. Can also plot differential
#' gene expression or general expression data if desired.
#' @param name_edge Vector of genes to plot.
#' @param col_ct Cell type column name.
#' @param edge_type Either "GEX" or "DGEA".
#' @param tx_size_col Column label text size.
#' @param tx_size_row Row label text size.
#' @param nudge_col Nudge column labels along y-axis.
#' @param nudge_row Nudge row labels along x-axis.
#' @param p_size Plot point size.
#' @param set_incr Step size between plot points.
#' @param lab_col_bound Boundary box y limit.
#' @param lab_row_bound Boundary box x limit.
#'
#' @return A ggplot2 object plotting individual annotation-level
#' data onto the HiVE base network.
#' @examples
#'
#' # ## HiVE edge panel
#' # hive_panel_edge(
#' #   stat_obj = d,
#' #   name_edge = c("ALOX5", "ALOX12", "ALOX15")
#' # )
#'
#' @export
hive_panel_edge <- function(
  stat_obj,
  name_edge,
  col_ct = "CellType",
  edge_type = "GEX",
  tx_size_col = 4,
  tx_size_row = 3,
  nudge_col = 0.025,
  nudge_row = -0.01,
  p_size = 8,
  set_incr = 0.03,
  lab_col_bound = 0.055,
  lab_row_bound = 0.045
) {
  # Load data
  net1 <- stat_obj
  if (edge_type == "GEX") {
    # Extract all lipid-related genes for the specified set
    net_genes <- name_edge
    net1 <- SeuratObject::FetchData(
      net1,
      vars = c(
        col_ct,
        net_genes[net_genes %in% rownames(net1)]
      )
    )
    if (col_ct != "CellType") {
      net1[["CellType"]] <- net1[[col_ct]]
      net1 <- dplyr::select(
        net1,
        -c(col_ct),
        "CellType", dplyr::everything()
      )
    }
    # calculate mean scaled expression per cell type
    net1[[1]] <- factor(
      as.character(net1[[1]]),
      levels = gtools::mixedsort(unique(as.character(net1[[1]])))
    )
    net1 <- as.data.frame(scale(
      as.matrix(
        magrittr::set_rownames(
          setNames(
            as.data.frame(
              lapply(
                net1[, 2:ncol(
                  net1
                )],
                function(x) {
                  dplyr::select(
                    aggregate(
                      x,
                      list(
                        net1[, 1]
                      ),
                      FUN = mean
                    ),
                    c(2)
                  )
                }
              )
            ),
            names(net1[, 2:ncol(net1)])
          ),
          levels(net1[, 1])
        )
      ),
      center = TRUE
    ))
  }
  if (edge_type == "DGEA") {
    # Extract all lipid-related genes
    # for the specified set
    net_genes <- name_edge
    net1 <- net1[
      net1[["GENE"]] %in% net_genes,
      c(col_ct, "GENE", "log2FC")
    ]
    # Convert cell type to factor and format as data frame
    net1[[col_ct]] <- factor(
      as.character(net1[[col_ct]]),
      levels = gtools::mixedsort(unique(as.character(net1[[col_ct]])))
    )
    if (col_ct != "CellType") {
      net1[["CellType"]] <- net1[[col_ct]]
      net1 <- dplyr::select(net1, -c(col_ct))
    }
    net1 <- reshape2::dcast(
      net1, CellType ~ GENE, value.var = "log2FC"
    )
    net1[is.na(net1)] <- 0
    net1 <- dplyr::select(
      magrittr::set_rownames(
        net1, levels(net1[["CellType"]])
      ),
      -c("CellType")
    )
  }
  #---- Edge attributes -----
  # Calculate x and y coordinates around origin
  ## Melt from wide to long
  np1 <- reshape2::melt(
    dplyr::mutate(net1, "CellType" = row.names(net1)),
    id.vars = "CellType"
  )
  ## Set steps between points and calculate coords
  ## Set all to the midpoint
  if (nrow(net1) == 1) {
    mid1 <- data.frame("x" = 0, "y" = 0)
    net1 <- cbind(net1, mid1)
  }
  if (nrow(net1) == 2) {
    mid1 <- data.frame(
      "x" = c(0 - set_incr, 0 + set_incr),
      "y" = rep(0, 2)
    )
    net1 <- cbind(net1, mid1)
  }
  if (nrow(net1) >= 3) {
    mid1 <- data.frame("x" = 0, "y" = 0)
    # create individual points for all observations around midpoint
    ## set x and y coord increments
    if (is.null(set_incr)) {
      if (nrow(net1) > 10) {
        num_x <- (1 / nrow(net1)) / 2
        num_y <- (1 / nrow(net1)) / 2
      }
      if (nrow(net1) < 10 && nrow(net1) > 5) {
        num_x <- (1 / nrow(net1)) / 4
        num_y <- (1 / nrow(net1)) / 4
      }
      if (nrow(net1) < 5) {
        num_x <- (1 / nrow(net1)) / 4
        num_y <- (1 / nrow(net1)) / 4
      }
    }
    if (!is.null(set_incr)) {
      num_x <- set_incr
      num_y <- set_incr
    }
    ## calculate coords for all points
    ### if rows and columns are even in length
    if (nrow(net1) %% 2 == 0 && ncol(net1) %% 2 == 0) {
      d_out <- data.frame(
        # determined by cell type
        "x" = rep(
          seq(
            from = mid1[["x"]] -
              (floor(nrow(net1) / 2) - 1) * num_x,
            to = mid1[["x"]] +
              (floor(nrow(net1) / 2)) * num_x,
            by = num_x
          ),
          ncol(net1)
        ),
        # determined by gene
        ## fix error with even number of row/column numbers
        "y" = sort(rep(
          seq(
            from = mid1[["y"]] -
              (floor(ncol(net1) / 2) - 1) * num_y,
            to = mid1[["y"]] +
              (floor(ncol(net1) / 2)) * num_y,
            by = num_y
          ),
          nrow(net1)
        ))
      )
    }
    ### if only rows are even
    if (nrow(net1) %% 2 == 0 && ncol(net1) %% 2 == 1) {
      d_out <- data.frame(
        # determined by cell type
        "x" = rep(
          seq(
            from = mid1[["x"]] -
              (floor(nrow(net1) / 2) - 1) * num_x,
            to = mid1[["x"]] +
              (floor(nrow(net1) / 2)) * num_x,
            by = num_x
          ),
          ncol(net1)
        ),
        # determined by gene
        ## fix error with even number of row/column numbers
        "y" = sort(rep(
          seq(
            from = mid1[["y"]] -
              (floor(ncol(net1) / 2)) * num_y,
            to = mid1[["y"]] +
              (floor(ncol(net1) / 2)) * num_y,
            by = num_y
          ),
          nrow(net1)
        ))
      )
    }
    ### if only columns are even
    if (nrow(net1) %% 2 == 1 && ncol(net1) %% 2 == 0) {
      d_out <- data.frame(
        # determined by cell type
        "x" = rep(
          seq(
            from = mid1[["x"]] -
              (floor(nrow(net1) / 2)) * num_x,
            to = mid1[["x"]] +
              (floor(nrow(net1) / 2)) * num_x,
            by = num_x
          ),
          ncol(net1)
        ),
        # determined by gene
        ## fix error with even number of row/column numbers
        "y" = sort(rep(
          seq(
            from = mid1[["y"]] -
              (floor(ncol(net1) / 2) - 1) * num_y,
            to = mid1[["y"]] +
              (floor(ncol(net1) / 2)) * num_y,
            by = num_y
          ),
          nrow(net1)
        ))
      )
    }
    ### if neither rows nor columns are even
    if (nrow(net1) %% 2 == 1 && ncol(net1) %% 2 == 1) {
      d_out <- data.frame(
        # determined by cell type
        "x" = rep(
          seq(
            from = mid1[["x"]] -
              (floor(nrow(net1) / 2)) * num_x,
            to = mid1[["x"]] +
              (floor(nrow(net1) / 2)) * num_x,
            by = num_x
          ),
          ncol(net1)
        ),
        # determined by gene
        ## fix error with even number of row/column numbers
        "y" = sort(rep(
          seq(
            from = mid1[["y"]] -
              (floor(ncol(net1) / 2)) * num_y,
            to = mid1[["y"]] +
              (floor(ncol(net1) / 2)) * num_y,
            by = num_y
          ),
          nrow(net1)
        ))
      )
    }
    net1 <- cbind(
      np1,
      d_out
    )
  }
  # Set row and column label coordinates
  ## set column label coords
  d_out2 <- as.data.frame(
    lapply(
      seq.int(1, 1, 1),
      function(i) {
        dout2a <- net1
        if (length(unique(dout2a[["variable"]])) == 1) {
          dout2b <- data.frame(
            "lab_col_x" = unique(dout2a[["x"]]),
            "lab_col_y" = rep(
              min(dout2a[["y"]]) -
                ((1 / length(unique(dout2a[["y"]]))) / 10),
              length(unique(dout2a[["x"]]))
            ),
            "CellType" = unique(dout2a[["CellType"]])
          )
        }
        if (length(unique(dout2a[["variable"]])) == 2) {
          dout2b <- data.frame(
            "lab_col_x" = unique(dout2a[["x"]]),
            "lab_col_y" = rep(
              min(dout2a[["y"]]) -
                ((1 / length(unique(dout2a[["y"]]))) / 4),
              length(unique(dout2a[["x"]]))
            ),
            "CellType" = unique(dout2a[["CellType"]])
          )
        }
        if (length(unique(dout2a[["variable"]])) > 2) {
          dout2b <- data.frame(
            "lab_col_x" = unique(dout2a[["x"]]),
            "lab_col_y" = rep(
              min(dout2a[["y"]]) -
                ((1 / length(unique(dout2a[["y"]]))) / 2),
              length(unique(dout2a[["x"]]))
            ),
            "CellType" = unique(dout2a[["CellType"]])
          )
        }
        return(dout2b) # nolint
      }
    )
  )
  # row name coords
  d_out3 <- as.data.frame(
    lapply(
      seq.int(1, 1, 1),
      function(i) {
        dout2a <- net1
        dout2b <- data.frame(
          "lab_row_x" = rep(
            min(dout2a[["x"]]) -
              ((1 / length(unique(dout2a[["x"]]))) / 10),
            length(unique(dout2a[["y"]]))
          ),
          "lab_row_y" = unique(dout2a[["y"]]),
          "GENE" = unique(dout2a[["variable"]])
        )
        return(dout2b) # nolint
      }
    )
  )
  # Scale fold change from 0 to 1 for node fill
  net1[["fill.edge"]] <- (
    net1[["value"]] - min(net1[["value"]], na.rm = TRUE)
  ) / (
    max(net1[["value"]], na.rm = TRUE) -
      min(net1[["value"]], na.rm = TRUE)
  )
  net1[["fill.edge"]] <- ifelse(
    net1[["value"]] == 0, 0.5,
    net1[["fill.edge"]]
  )
  ### define color scale
  col_fun <- colorRampPalette(col_grad(scm = 5))
  col_len <- col_fun(length(net1[["fill.edge"]]))
  net1[["fill.edge.names"]] <- col_len
  ### Set boundary box sizes
  np_edge_box <- lapply(
    seq.int(1, 1, 1),
    function(i) {
      d1 <- net1
      d2 <- dplyr::bind_rows(
        lapply(
          seq.int(1, nrow(d1), 1),
          function(j) {
            d1a <- d1[j, c("x", "y")]
            d2a <- data.frame(
              "x" = c(
                d1a[["x"]] - lab_row_bound,
                d1a[["x"]] + 0.015,
                d1a[["x"]] + 0.015,
                d1a[["x"]] - lab_row_bound
              ),
              "y" = c(
                d1a[["y"]] + 0.015,
                d1a[["y"]] + 0.015,
                d1a[["y"]] - lab_col_bound,
                d1a[["y"]] - lab_col_bound
              )
            )
            d2a[["pw"]] <- i
            return(d2a) # nolint
          }
        )
      )
      d3 <- sf::st_as_sf(d2, coords = c("x", "y"))
      d4 <- concaveman::concaveman(d3, concavity = 1)
      d4[["pw"]] <- i
      return(d4) # nolint
    }
  )
  np_edge_box <- do.call(rbind, np_edge_box)
  # Plot
  np2 <- ggplot2::ggplot(data = np1) +
    # Edge expression point boundary boxes
    ggplot2::geom_sf(
      data = np_edge_box,
      ggplot2::aes(
        fill = .data[["pw"]]
      ),
      color = "grey25",
      fill = "grey75",
      alpha = 0.9
    ) +
    # Edge labels
    ggplot2::geom_text(
      data = d_out3,
      ggplot2::aes(
        x = d_out3[["lab_row_x"]],
        y = d_out3[["lab_row_y"]],
        label = d_out3[["GENE"]]
      ),
      size = tx_size_row,
      hjust = 1,
      nudge_x = nudge_row,
      color = "grey10"
    ) +
    ggplot2::geom_text(
      data = d_out2,
      ggplot2::aes(
        x = d_out2[["lab_col_x"]],
        y = d_out2[["lab_col_y"]],
        label = d_out2[["CellType"]]
      ),
      size = tx_size_col,
      angle = 90,
      hjust = 1,
      nudge_y = nudge_col,
      color = "grey10"
    ) +
    # Edge points
    ggraph::geom_node_point(
      data = net1,
      ggplot2::aes(
        x = net1[["x"]],
        y = net1[["y"]],
        fill = net1[["fill.edge"]]
      ),
      shape = 22,
      size = p_size,
      color = "black",
      show.legend = FALSE
    ) +
    ggplot2::scale_fill_continuous(
      palette = col_grad(scm = 5)
    ) +
    # plot theme
    gen_theme() + # nolint
    net_theme() # nolint
  return(np2) # nolint
}
